/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: plaggy (https://sketchfab.com/plaggy)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cc0-paper-b0776948a05f4766a03856223344b264
title: CC0 - Paper
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/whitePaper.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.06, 0, -0.02]} scale={0.03}>
            <mesh geometry={nodes.Paper_Paper_0.geometry} material={materials.Paper} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/whitePaper.gltf')
