/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: BlackCube (https://sketchfab.com/blackcube4)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lamborghini-aventador-with-interior-36eb1fa54a0d4be695d4cd90c30f4ff1
title: Lamborghini Aventador with Interior
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/aventador.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.85}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 10.26, -0.63]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Headlights_Front_Light_0.geometry} material={materials.Front_Light} />
            <mesh geometry={nodes.Headlights_Carbon_0.geometry} material={materials.Carbon} />
            <mesh geometry={nodes.Headlights_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Headlights_Glass_Lights_0.geometry} material={materials.Glass_Lights} />
            <mesh geometry={nodes.Headlights_Front_Light_Lens_0.geometry} material={materials.Front_Light_Lens} />
          </group>
          <group position={[0, 10.26, -0.63]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Headlights_Glass_Glass_Lights_0.geometry} material={materials.Glass_Lights} />
          </group>
          <group position={[0.2, 9.83, -1.2]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Taillights_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Taillights_Aluminum_0.geometry} material={materials.Aluminum} />
            <mesh geometry={nodes.Taillights_Carbon_0.geometry} material={materials.Carbon} />
            <mesh geometry={nodes.Taillights_Dark_Metal_0.geometry} material={materials.Dark_Metal} />
            <mesh geometry={nodes.Taillights_Red_Lights_0.geometry} material={materials.Red_Lights} />
            <mesh geometry={nodes.Taillights_Orange_Lights_0.geometry} material={materials.Orange_Lights} />
          </group>
          <group position={[0.2, 9.83, -1.2]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Taillights_Glass_Glass_Lights_0.geometry} material={materials.Glass_Lights} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Front_Window_Window_Glass_0.geometry} material={materials.Window_Glass} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Back_Side_Windows_Window_Glass_0.geometry} material={materials.Window_Glass} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Door_Windows_Window_Glass_0.geometry} material={materials.Window_Glass} />
          </group>
          <group position={[0, 109.83, -61.62]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Back_Window_Window_Glass_0.geometry} material={materials.Window_Glass} />
          </group>
          <group scale={100}>
            <mesh geometry={nodes.Caps_Carbon_0.geometry} material={materials.Carbon} />
          </group>
          <group position={[0, -4.34, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Wheels_Carbon_0.geometry} material={materials.Carbon} />
            <mesh geometry={nodes.Wheels_Hubcap_0.geometry} material={materials.Hubcap} />
            <mesh geometry={nodes.Wheels_Wheel_Screw_0.geometry} material={materials.Wheel_Screw} />
            <mesh geometry={nodes.Wheels_Wheel_Screw_0_1.geometry} material={materials.Wheel_Screw} />
          </group>
          <group position={[0, -4.34, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Tires_Tires_0.geometry} material={materials.Tires} />
            <mesh geometry={nodes.Tires_Tires_0_1.geometry} material={materials.Tires} />
            <mesh geometry={nodes.Tires_Tires_0_2.geometry} material={materials.Tires} />
            <mesh geometry={nodes.Tires_Tires_0_3.geometry} material={materials.Tires} />
            <mesh geometry={nodes.Tires_Tires_2_0.geometry} material={materials.Tires_2} />
          </group>
          <group position={[0, -4.34, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Brake_Carbon_0.geometry} material={materials.Carbon} />
            <mesh geometry={nodes.Brake_Body_0.geometry} material={materials.Body} />
            <mesh geometry={nodes.Brake_Brake_wire_0.geometry} material={materials.Brake_wire} />
            <mesh geometry={nodes.Brake_Brake_2_0.geometry} material={materials.Brake_2} />
          </group>
          <group position={[0, -4.34, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Brake_disk_new_Brake_disk_0.geometry} material={materials.Brake_disk} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Door_Carbon_0.geometry} material={materials.Carbon} />
            <mesh geometry={nodes.Door_Body_0.geometry} material={materials.Body} />
            <mesh geometry={nodes.Door_Aluminum_0.geometry} material={materials.Aluminum} />
          </group>
          <group position={[0, 109.83, -61.62]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.EngineHood_Dark_Metal_0.geometry} material={materials.Dark_Metal} />
            <mesh geometry={nodes.EngineHood_Undercarriage_0.geometry} material={materials.Undercarriage} />
            <mesh geometry={nodes.EngineHood_Carbon_0.geometry} material={materials.Carbon} />
          </group>
          <group position={[0, 75.54, 132.39]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Trunk_Carbon_0.geometry} material={materials.Carbon} />
          </group>
          <group position={[-0.01, 10.32, -0.65]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Undercarriage_Undercarriage_0.geometry} material={materials.Undercarriage} />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={100}>
            <mesh geometry={nodes.Front_Fins_Dark_Metal_0.geometry} material={materials.Dark_Metal} />
          </group>
          <group rotation={[Math.PI, 0, Math.PI]} scale={100}>
            <mesh geometry={nodes.Mid_Fins_Carbon_0.geometry} material={materials.Carbon} />
          </group>
          <group position={[0, 91.35, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Exhaust_Exhaust_0.geometry} material={materials.Exhaust} />
          </group>
          <group scale={100}>
            <mesh geometry={nodes.Back_Fins_Carbon_0.geometry} material={materials.Carbon} />
          </group>
          <group position={[0.12, 80.14, -228.49]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Lamborghini_Gold_0.geometry} material={materials.Gold} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Body_Body_0.geometry} material={materials.Body} />
            <mesh geometry={nodes.Body_Aluminum_0.geometry} material={materials.Aluminum} />
            <mesh geometry={nodes.Body_Carbon_0.geometry} material={materials.Carbon} />
            <mesh geometry={nodes.Body_Carbon_0_1.geometry} material={materials.Carbon} />
            <mesh geometry={nodes.Body_Dark_Metal_0.geometry} material={materials.Dark_Metal} />
            <mesh geometry={nodes.Body_Chrome_0.geometry} material={materials.Chrome} />
            <mesh geometry={nodes.Body_Window_Glass_0.geometry} material={materials.Window_Glass} />
            <mesh geometry={nodes.Body_Undercarriage_0.geometry} material={materials.Undercarriage} />
            <mesh geometry={nodes.Body_Glass_Lights_0.geometry} material={materials.Glass_Lights} />
          </group>
          <group position={[0, -0.26, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Emblem_Emblem_0.geometry} material={materials.Emblem} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Mirror_Mirror_0.geometry} material={materials.Mirror} />
          </group>
          <group position={[0, 12.53, -0.09]} scale={100}>
            <mesh geometry={nodes.Inner_door_left_Dark_Metal_0.geometry} material={materials.Dark_Metal} />
            <mesh geometry={nodes.Inner_door_left_Glossy_Black_0.geometry} material={materials.Glossy_Black} />
            <mesh geometry={nodes.Inner_door_left_Interior_0.geometry} material={materials.Interior} />
            <mesh geometry={nodes.Inner_door_left_Mesh_0.geometry} material={materials.Mesh} />
          </group>
          <group position={[0, 12.53, 0]} scale={100}>
            <mesh geometry={nodes.Inner_door_right_Dark_Metal_0.geometry} material={materials.Dark_Metal} />
            <mesh geometry={nodes.Inner_door_right_Interior_0.geometry} material={materials.Interior} />
            <mesh geometry={nodes.Inner_door_right_Glossy_Black_0.geometry} material={materials.Glossy_Black} />
            <mesh geometry={nodes.Inner_door_right_Mesh_0.geometry} material={materials.Mesh} />
          </group>
          <group position={[0, 12.53, 0]} scale={100}>
            <mesh geometry={nodes.Seam_Logo_on_Seats_0.geometry} material={materials.Logo_on_Seats} />
          </group>
          <group position={[0, 12.53, 0]} scale={100}>
            <mesh geometry={nodes.Motor_Engine_0.geometry} material={materials.Engine} />
          </group>
          <group position={[0, 12.53, 0]} scale={100}>
            <mesh geometry={nodes.Display_Display_0.geometry} material={materials.Display} />
          </group>
          <group position={[0, 12.53, 0]} scale={100}>
            <mesh geometry={nodes.Rear_mirror_Mirror_0.geometry} material={materials.Mirror} />
          </group>
          <group position={[0, 12.53, 0]} scale={100}>
            <mesh geometry={nodes.Window_base_Glossy_Black_0.geometry} material={materials.Glossy_Black} />
          </group>
          <group position={[0, 12.53, 0]} scale={100}>
            <mesh geometry={nodes.Sticker_Sticker_0.geometry} material={materials.Sticker} />
          </group>
          <group position={[0, 12.53, 0]} scale={100}>
            <mesh geometry={nodes.Interior_Interior_0.geometry} material={materials.Interior} />
            <mesh geometry={nodes.Interior_Floor_Grid_0.geometry} material={materials.Floor_Grid} />
            <mesh geometry={nodes.Interior_Darker_Metal_0.geometry} material={materials.Darker_Metal} />
            <mesh geometry={nodes.Interior_Logo_on_Seats_0.geometry} material={materials.Logo_on_Seats} />
            <mesh geometry={nodes.Interior_Sticker_0.geometry} material={materials.Sticker} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/aventador.gltf')
