/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Abhishek walia (https://sketchfab.com/abhisheekwalia)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/racing-4039d39ab44a4e10a6f62ce33b269395
title: Racing
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/roadMap.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-95.02, 36.29, -651.85]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Cube_4__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group position={[-95.02, 36.29, -651.85]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Cube__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group position={[-95.02, 36.29, -651.85]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Cube_8__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group position={[-95.02, 36.29, -651.85]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Cube_9__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group position={[-95.02, 36.29, -651.85]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Cube_7__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group position={[-95.02, 36.29, -651.85]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Cube_6__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group position={[-95.02, 36.29, -651.85]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Cube_5__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group position={[-95.02, 36.29, -651.85]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Cube_3__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group position={[-95.02, 36.29, -651.85]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Cube_2__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group position={[-95.02, 36.29, -651.85]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Cube_1__0.geometry} material={materials['Scene_-_Root']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/roadMap.gltf')
