/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: bobymonsuta (https://sketchfab.com/bobymonsuta)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/chinese-road-signs-32-road-signs-and-more-241ed4fd2fc145259ff9b51bd6f04877
title: Chinese Road Signs (32 road signs and more)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/roadSigns.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-416.15, 198.33, 377.36]}>
            <group position={[-73.85, 0, -110.77]}>
              <group position={[0, 0, 270]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_Turn_right_0.geometry} material={materials.Turn_right} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, 210]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_2_Turn_left_orand_right_0.geometry} material={materials.Turn_left_orand_right} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_2_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_2_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_2_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_2_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_2_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, 150]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_3_Turn_left_0.geometry} material={materials.Turn_left} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_3_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_3_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_3_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_3_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_3_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, 90]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_4_Roundabout_0.geometry} material={materials.Roundabout} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_4_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_4_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_4_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_4_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_4_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, 30]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_5_Proceed_straight_or_right_0.geometry} material={materials.Proceed_straight_or_right} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_5_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_5_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_5_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_5_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_5_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, -30]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_6_Proceed_straight_or_left_0.geometry} material={materials.Proceed_straight_or_left} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_6_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_6_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_6_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_6_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_6_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, -90]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_7_Proceed_straight_0.geometry} material={materials.Proceed_straight} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_7_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_7_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_7_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_7_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_7_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, -150]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_8_Keep_right_side_only_0.geometry} material={materials.Keep_right_side_only} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_8_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_8_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_8_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_8_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_8_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, -210]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_9_Keep_left_side_only_0.geometry} material={materials.Keep_left_side_only} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_9_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_9_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_9_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_9_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_9_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, -270]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_10_Bicycles_only_0.geometry} material={materials.Bicycles_only} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_10_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_10_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_10_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_10_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_10_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
            </group>
            <group position={[46.15, 0, 99.23]}>
              <group position={[0, 0, 420]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_11_No_entry_for_vehicular_traffic_0.geometry} material={materials.No_entry_for_vehicular_traffic} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_11_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_11_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_11_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_11_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_11_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, 360]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_12_No_u_turn_0.geometry} material={materials.No_u_turn} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_12_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_12_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_12_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_12_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_12_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, 300]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_13_No_straight_or_right_turn_0.geometry} material={materials.No_straight_or_right_turn} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_13_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_13_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_13_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_13_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_13_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, 240]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_14_No_straight_or_left_turn_0.geometry} material={materials.No_straight_or_left_turn} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_14_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_14_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_14_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_14_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_14_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, 180]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_15_No_stopping_0.geometry} material={materials.No_stopping} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_15_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_15_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_15_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_15_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_15_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, 120]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_16_No_right_turn_0.geometry} material={materials.No_right_turn} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_16_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_16_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_16_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_16_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_16_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, 60]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_17_No_pedestrians_0.geometry} material={materials.No_pedestrians} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_17_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_17_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_17_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_17_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_17_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes.Base_LP_50_circle_18_No_parking_0.geometry} material={materials.No_parking} />
              </group>
              <group position={[0, -3.33, -1.48]}>
                <group position={[0, 35, -3.25]}>
                  <group position={[0, -10, 0]}>
                    <mesh geometry={nodes.Fixation_down_LP_18_Fixation_0.geometry} material={materials.Fixation} />
                  </group>
                  <group position={[0, 10, 0]}>
                    <mesh geometry={nodes.Fixation_up_LP_18_Fixation_0.geometry} material={materials.Fixation} />
                  </group>
                </group>
                <group position={[0, 35, 5.06]}>
                  <group position={[0, -10, 0]}>
                    <mesh geometry={nodes.Support_LP__down_18_Support_0.geometry} material={materials.Support} />
                  </group>
                  <group position={[0, 10, 0]}>
                    <mesh geometry={nodes.Support_LP__up_18_Support_0.geometry} material={materials.Support} />
                  </group>
                </group>
                <group position={[0, -70, -1.81]}>
                  <mesh geometry={nodes.Pole_LP_18_Pole_0.geometry} material={materials.Pole} />
                </group>
              </group>
              <group position={[0, 0, -60]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_19_No_motor_vehicles_0.geometry} material={materials.No_motor_vehicles} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_19_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_19_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_19_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_19_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_19_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, -120]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_20_No_left_turn_0.geometry} material={materials.No_left_turn} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_20_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_20_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_20_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_20_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_20_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, -180]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_21_No_left_turn_0.geometry} material={materials.No_left_turn_0} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_21_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_21_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_21_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_21_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_21_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, -240]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_22_No_freight_vehicles_0.geometry} material={materials.No_freight_vehicles} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_22_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_22_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_22_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_22_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_22_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, -300]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_23_No_entry_for_vehiculars_and_pedestrians_0.geometry} material={materials.No_entry_for_vehiculars_and_pedestrians} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_23_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_23_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_23_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_23_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_23_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, -360]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_24_No_buses_0.geometry} material={materials.No_buses} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_24_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_24_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_24_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_24_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_24_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, -420]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_25_No_bicycles_0.geometry} material={materials.No_bicycles} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_25_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_25_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_25_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_25_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_25_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
              <group position={[0, 0, -480]}>
                <group position={[0, 31.67, 3.41]} rotation={[Math.PI / 2, 0, 0]}>
                  <mesh geometry={nodes.Base_LP_50_circle_26_Give_way_to_oncoming_traffing_0.geometry} material={materials.Give_way_to_oncoming_traffing} />
                </group>
                <group position={[0, -3.33, -1.48]}>
                  <group position={[0, 35, -3.25]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Fixation_down_LP_26_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Fixation_up_LP_26_Fixation_0.geometry} material={materials.Fixation} />
                    </group>
                  </group>
                  <group position={[0, 35, 5.06]}>
                    <group position={[0, -10, 0]}>
                      <mesh geometry={nodes.Support_LP__down_26_Support_0.geometry} material={materials.Support} />
                    </group>
                    <group position={[0, 10, 0]}>
                      <mesh geometry={nodes.Support_LP__up_26_Support_0.geometry} material={materials.Support} />
                    </group>
                  </group>
                  <group position={[0, -70, -1.81]}>
                    <mesh geometry={nodes.Pole_LP_26_Pole_0.geometry} material={materials.Pole} />
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group position={[-250, 212.5, 57.56]}>
            <group position={[0, 0, 60]}>
              <group position={[0, 17.5, 2.44]}>
                <mesh geometry={nodes.Base_LP_square_Parking_place_0.geometry} material={materials.Parking_place} />
              </group>
              <group position={[0, -17.5, -2.44]}>
                <group position={[0, 35, -3.25]}>
                  <group position={[0, -10, 0]}>
                    <mesh geometry={nodes.Fixation_down_LP_27_Fixation_0.geometry} material={materials.Fixation} />
                  </group>
                  <group position={[0, 10, 0]}>
                    <mesh geometry={nodes.Fixation_up_LP_27_Fixation_0.geometry} material={materials.Fixation} />
                  </group>
                </group>
                <group position={[0, 35, 5.06]}>
                  <group position={[0, -10, -0.3]}>
                    <mesh geometry={nodes.Support_LP__down_27_Support_0.geometry} material={materials.Support} />
                  </group>
                  <group position={[0, 10, -0.3]}>
                    <mesh geometry={nodes.Support_LP__up_27_Support_0.geometry} material={materials.Support} />
                  </group>
                </group>
                <group position={[0, -70, -1.81]}>
                  <mesh geometry={nodes.Pole_LP_27_Pole_0.geometry} material={materials.Pole} />
                </group>
              </group>
            </group>
            <group position={[0, 17.5, 2.44]}>
              <mesh geometry={nodes.Base_LP_square_2_Disables_parking_0.geometry} material={materials.Disables_parking} />
            </group>
            <group position={[0, -17.5, -2.44]}>
              <group position={[0, 35, -3.25]}>
                <group position={[0, -10, 0]}>
                  <mesh geometry={nodes.Fixation_down_LP_28_Fixation_0.geometry} material={materials.Fixation} />
                </group>
                <group position={[0, 10, 0]}>
                  <mesh geometry={nodes.Fixation_up_LP_28_Fixation_0.geometry} material={materials.Fixation} />
                </group>
              </group>
              <group position={[0, 35, 5.06]}>
                <group position={[0, -10, -0.3]}>
                  <mesh geometry={nodes.Support_LP__down_28_Support_0.geometry} material={materials.Support} />
                </group>
                <group position={[0, 10, -0.3]}>
                  <mesh geometry={nodes.Support_LP__up_28_Support_0.geometry} material={materials.Support} />
                </group>
              </group>
              <group position={[0, -70, -1.81]}>
                <mesh geometry={nodes.Pole_LP_28_Pole_0.geometry} material={materials.Pole} />
              </group>
            </group>
            <group position={[0, 0, -60]}>
              <group position={[0, 17.5, 2.44]}>
                <mesh geometry={nodes.Base_LP_square_3_Crosswalk_0.geometry} material={materials.Crosswalk} />
              </group>
              <group position={[0, -17.5, -2.44]}>
                <group position={[0, 35, -3.25]}>
                  <group position={[0, -10, 0]}>
                    <mesh geometry={nodes.Fixation_down_LP_29_Fixation_0.geometry} material={materials.Fixation} />
                  </group>
                  <group position={[0, 10, 0]}>
                    <mesh geometry={nodes.Fixation_up_LP_29_Fixation_0.geometry} material={materials.Fixation} />
                  </group>
                </group>
                <group position={[0, 35, 5.06]}>
                  <group position={[0, -10, -0.3]}>
                    <mesh geometry={nodes.Support_LP__down_29_Support_0.geometry} material={materials.Support} />
                  </group>
                  <group position={[0, 10, -0.3]}>
                    <mesh geometry={nodes.Support_LP__up_29_Support_0.geometry} material={materials.Support} />
                  </group>
                </group>
                <group position={[0, -70, -1.81]}>
                  <mesh geometry={nodes.Pole_LP_29_Pole_0.geometry} material={materials.Pole} />
                </group>
              </group>
            </group>
          </group>
          <group position={[-120, 212.5, -2.44]}>
            <group position={[0, 17.5, 2.44]}>
              <mesh geometry={nodes.Base_LP_octogone_basenew_Stop_0.geometry} material={materials.Stop} />
            </group>
            <group position={[0, -17.5, -2.44]}>
              <group position={[0, 35, -3.25]}>
                <group position={[0, -10, 0]}>
                  <mesh geometry={nodes.Fixation_down_LP_30_Fixation_0.geometry} material={materials.Fixation} />
                </group>
                <group position={[0, 10, 0]}>
                  <mesh geometry={nodes.Fixation_up_LP_30_Fixation_0.geometry} material={materials.Fixation} />
                </group>
              </group>
              <group position={[0, 35, 5.06]}>
                <group position={[0, -10, 0.95]}>
                  <mesh geometry={nodes.Support_LP__down_30_Support_0.geometry} material={materials.Support} />
                </group>
                <group position={[0, 10, 0.95]}>
                  <mesh geometry={nodes.Support_LP__up_30_Support_0.geometry} material={materials.Support} />
                </group>
              </group>
              <group position={[0, -70, -1.81]}>
                <mesh geometry={nodes.Pole_LP_30_Pole_0.geometry} material={materials.Pole} />
              </group>
            </group>
          </group>
          <group position={[0, 208.33, 27.56]}>
            <group position={[0, 0, 30]}>
              <group position={[0, 13.33, 2.44]}>
                <mesh geometry={nodes.Base_LP_triangle_Give_way_0.geometry} material={materials.Give_way} />
              </group>
              <group position={[0, -13.33, -2.44]}>
                <group position={[0, 35, -3.25]}>
                  <group position={[0, 0.77, 0]}>
                    <mesh geometry={nodes.Fixation_down_LP_31_Fixation_0.geometry} material={materials.Fixation} />
                  </group>
                  <group position={[0, 10, 0]}>
                    <mesh geometry={nodes.Fixation_up_LP_31_Fixation_0.geometry} material={materials.Fixation} />
                  </group>
                </group>
                <group position={[0, 35, 5.06]}>
                  <group position={[0, 0.77, 0]}>
                    <mesh geometry={nodes.Support_LP__down_31_Support_0.geometry} material={materials.Support} />
                  </group>
                  <group position={[0, 10, 0]}>
                    <mesh geometry={nodes.Support_LP__up_31_Support_0.geometry} material={materials.Support} />
                  </group>
                </group>
                <group position={[0, -70, -1.81]}>
                  <mesh geometry={nodes.Pole_LP_31_Pole_0.geometry} material={materials.Pole} />
                </group>
              </group>
            </group>
            <group position={[0, 0, -30]}>
              <group position={[0, 13.33, 2.44]}>
                <mesh geometry={nodes.Base_LP_triangle_2_Slow_0.geometry} material={materials.Slow} />
              </group>
              <group position={[0, -13.33, -2.44]}>
                <group position={[0, 35, -3.25]}>
                  <group position={[0, 0.77, 0]}>
                    <mesh geometry={nodes.Fixation_down_LP_32_Fixation_0.geometry} material={materials.Fixation} />
                  </group>
                  <group position={[0, 10, 0]}>
                    <mesh geometry={nodes.Fixation_up_LP_32_Fixation_0.geometry} material={materials.Fixation} />
                  </group>
                </group>
                <group position={[0, 35, 5.06]}>
                  <group position={[0, 0.77, 0]}>
                    <mesh geometry={nodes.Support_LP__down_32_Support_0.geometry} material={materials.Support} />
                  </group>
                  <group position={[0, 10, 0]}>
                    <mesh geometry={nodes.Support_LP__up_32_Support_0.geometry} material={materials.Support} />
                  </group>
                </group>
                <group position={[0, -70, -1.81]}>
                  <mesh geometry={nodes.Pole_LP_32_Pole_0.geometry} material={materials.Pole} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/roadSigns.gltf')
