/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: bobymonsuta (https://sketchfab.com/bobymonsuta)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/chinese-road-signs-32-road-signs-and-more-241ed4fd2fc145259ff9b51bd6f04877
title: Chinese Road Signs (32 road signs and more)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/roadSigns.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-416.15, 198.33, 377.36]}>
            <group position={[-73.85, 0, -110.77]}>
          <group position={[-120, 212.5, -2.44]}>
            <group position={[0, 17.5, 2.44]}>
              <mesh geometry={nodes.Base_LP_octogone_basenew_Stop_0.geometry} material={materials.Stop} />
            </group>
            <group position={[0, -17.5, -2.44]}>
              <group position={[0, 35, -3.25]}>
                <group position={[0, -10, 0]}>
                  <mesh geometry={nodes.Fixation_down_LP_30_Fixation_0.geometry} material={materials.Fixation} />
                </group>
                <group position={[0, 10, 0]}>
                  <mesh geometry={nodes.Fixation_up_LP_30_Fixation_0.geometry} material={materials.Fixation} />
                </group>
              </group>
              <group position={[0, 35, 5.06]}>
                <group position={[0, -10, 0.95]}>
                  <mesh geometry={nodes.Support_LP__down_30_Support_0.geometry} material={materials.Support} />
                </group>
                <group position={[0, 10, 0.95]}>
                  <mesh geometry={nodes.Support_LP__up_30_Support_0.geometry} material={materials.Support} />
                </group>
              </group>
            </group>
          </group>
        </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/roadSigns.gltf')
